baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "MLSys CDT"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "EPSRC MLSys CDT"
  description: "EPSRC MLSys CDT"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&edition=2024&id=1118"
    # instagram: "#"
    # facebook: "#"
    # twitter: "#"
  
  # backgroundImage:
  #   - "images/home-image.jpeg"

  location:
    - "School of Informatics, 10 Crichton Street, Edinburgh, EH8 9AB"
  #   - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "igs@inf.ed.ac.uk"
    - "futurestudents@ed.ac.uk"
    - "+44 (0)131 651 1208"

  copyright: "© 2024 MLSysCDT All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "About"
      url: "/about"
      weight: 2

  buttons:
    - name: "Contact"
      url: "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&edition=2024&id=1118"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "About"
      url: "/about"
      weight: 2

taxonomies:
  series: "series"
  tags: "tags"
