baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'graysx-modified'

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

[[menu.main]]
  name = "People"
  URL = "#people"
  weight = 2

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 3

 
  [[menu.main]]
  name = "Apply"
  URL = "#apply"
  weight = 4
 
  [[menu.main]]
  name = "Contact"
  URL = "#contact"
  weight = 5
  
